// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvTXmuUKA-tL--JRPjP2hT57ewhjJ7Lw',
    appId: '1:447302528923:web:8d2a6368fbc47209f8bb3e',
    messagingSenderId: '447302528923',
    projectId: 'flexed-f275f',
    authDomain: 'flexed-f275f.firebaseapp.com',
    storageBucket: 'flexed-f275f.appspot.com',
    measurementId: 'G-V0FMNT60D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjLbYAmAuja_cLBR1IEQgW7XeQrCmI-58',
    appId: '1:447302528923:android:bae93ed084731ffaf8bb3e',
    messagingSenderId: '447302528923',
    projectId: 'flexed-f275f',
    storageBucket: 'flexed-f275f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ6-OZrVl7P3fieE8Uyx4XHu4arXrc7wU',
    appId: '1:447302528923:ios:437a72ff049c0d60f8bb3e',
    messagingSenderId: '447302528923',
    projectId: 'flexed-f275f',
    storageBucket: 'flexed-f275f.appspot.com',
    iosClientId: '447302528923-m7gmnm5l5f0fq2qd1vtrq9lfc5fqgsdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ6-OZrVl7P3fieE8Uyx4XHu4arXrc7wU',
    appId: '1:447302528923:ios:b0b33a8b0b818e40f8bb3e',
    messagingSenderId: '447302528923',
    projectId: 'flexed-f275f',
    storageBucket: 'flexed-f275f.appspot.com',
    iosClientId: '447302528923-8n7v7gpkuogllko8pnrl9j71vup7qh4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexEducation.RunnerTests',
  );
}
